### ISSUE TITLE
Creación de nuevo sitio hospinet 2015

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#104]
Será utilizado como ambiente desarrollo para los nuevos cambios solicitados.

ya comprado el hosting en Amazón. Esperando notificacion de alta y Deployment del software.

**Comment by Exian** [comment]
Ha

Enviado desde Yahoo Mail en Android

**Comment by SpectralAngel** [comment]
Esperando a que se cree el nodo de la base de datos, casi todo listo
