### ISSUE TITLE
Error Severidad 4 - Correo electrónico en Perfil de usuario y Datos personales

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#109]
En el perfil ya tenemos registrado un correo electrónico y al registrar los datos personales, lo vuelve a pedir.

Deberíamos hacer que ambos sean el mismo. Si lo cambian en Datos personales o a través del botón de cambiar correo electrónico, se actualicen en ambos campos

![image](https://cloud.githubusercontent.com/assets/10442175/5690004/78337ef6-9838-11e4-964f-57c582a1c579.png)

![image](https://cloud.githubusercontent.com/assets/10442175/5690014/b4e8cf40-9838-11e4-8225-b172c7789d66.png)

**Comment by SpectralAngel** [comment]
Necesita algunos cambios internos, pero estoy en eso

**Comment by SpectralAngel** [comment]
Actualmente bloqueado en #114, no se puede avanzar hasta que no corrija ese problema
