### ISSUE TITLE
Error Severidad 4 - Colores del objeto para ingresar fechas

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#111]
La combinación de colores del objeto utilizado para colocar la fecha  no permite ver ni el valor seleccionado de mes y año ni los valores disponibles en las listas.

![image](https://cloud.githubusercontent.com/assets/10442175/5690060/91246568-983a-11e4-954e-1b4a7c73c8c7.png)

**Comment by SpectralAngel** [comment]
Corregido en 6605f68288e7960daf3211d4a567ac834acf6cc3
