### ISSUE TITLE
Error Severidad 4 - Problemas para mostrar acentos

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#112]
Hay problemas con los acentos  en la lista de países para la nacionalidad.Seria bueno revisar que el problema de los acentos, no ocurra en otros campos de otros formularios...

Colocar en orden alfabético el listbox

![image](https://cloud.githubusercontent.com/assets/10442175/5690079/1b74e60c-983b-11e4-9a93-fcfd449ff232.png)

**Comment by SpectralAngel** [comment]
Es un problema de la librería de Paises, si se observa Papúa esta bien escrito

**Comment by ZXLegolas** [comment]
Carlos, sacame de la lista de correos.

2015-01-12 14:55 GMT-06:00 Carlos Flores <notifications@github.com>:

**Comment by SpectralAngel** [comment]
Tenes que entrar a github y darle unfollow, sino te va a seguri mandando
correos, ya te saque de la lista de colaboradores

Carlos Flores

**Comment by luisdavid1962** [comment]
¿Donde está la biblioteca de Países? ¿no lo puedo arreglar?
