### ISSUE TITLE
Error Severidad 4 - Validación de formato de doc de identidad.

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#114]
Se puede ingresar la cantidad de dígitos o incluso letras en el campo sin restriccion, 

Debería validarse la cantidad y el tipo de dígitos 

y colocar un texto con la explicación de como ingresar el número 

![image](https://cloud.githubusercontent.com/assets/10442175/5690137/8ed7f02e-983d-11e4-80f4-81e6a9aa1223.png)

**Comment by SpectralAngel** [comment]
Esta tomando más tiempo de lo que creí, como la validación depende del campo anterior estoy teniendo problemas en cuanto al encadenamiento, a veces me lo valida a veces no, tengo especial problema entre los pasaportes y la identidad, estos me estan creando conflictos
