### ISSUE TITLE
Cambio Importancia 2 - Unificar perfil y datos personales 

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#116]
Desaparecer las pestañas de Perfil y de datos personales, hacer que ambos sean uno solo.

El botón de editar datos personales, debe ser el único que quede activo, desaparecer el botón de "modificar mi perfil"

Los campos de nombre, apellidos y fotos deben ingresarse o modificarse solo en datos personales. 
Que la opción de privacidad del perfil, sea manejada por el administrador desde la administración, no por el usuario. (Colocar en el formulario de administración, una leyenda de explicación de ¿que significa cada tipo de privacidad?)

**Comment by SpectralAngel** [comment]
Se unieron las pestañas de perfil y datos personales en bdf7a9f6937f49a9b99001b32ca38cfac11fd335, lo demás necesita algunos cambios internos bastante grandes.

**Comment by luisdavid1962** [comment]
Realmente este Issue, no debe cerrarse, está atendido y simplificado en
cierta forma, pero debemos dejarlo abierto hasta que solucionemos todos los
cambios...


Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts

**Comment by SpectralAngel** [comment]
Duplicado de #109

**Comment by SpectralAngel** [comment]
Lo cerre por que este es el mismo que el #109, lo voy a mantener cerrado
