### ISSUE TITLE
Error Severidad 2 - Problemas con correo del perfil

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#117]
Cuando se asocia un correo por primera vez, se envía un correo a la dirección de correo y el link generado que llega en el correo y que sirve para verificar la dirección dice "example.com" como dominio y no hospinet.epsmedical.com

Cuando se intenta modificar el correo, el sistema dice enviar un correo para confirmar que nunca llega.

**Comment by SpectralAngel** [comment]
Se cambio la url desde donde se generán los correos, verificar si esta funcionando bien

**Comment by luisdavid1962** [comment]
Ya puedo asociar el correo al usuario, el link está OK... pero no llega el
correo si quiero hacer un cambio.


Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts

2015-01-10 0:44 GMT-06:00 Carlos Flores <notifications@github.com>:

**Comment by SpectralAngel** [comment]
Se corrigió la configuración de envios de correo del sofware, ya se envia correctamente
