### ISSUE TITLE
Error Severidad 2 - No puede cambiar contraseña

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#118]
La usuaria Bessy.Gomez cuyo password es bessy123, trata de cambiar su contraseña y la pantalla queda en blanco.

![image](https://cloud.githubusercontent.com/assets/10442175/5690256/320cca44-9843-11e4-9973-aee1a95bb2fa.png)

**Comment by SpectralAngel** [comment]
Se agregaron los permisos a todos los usuarios nuevos y se corrigio el codigo que los asinga al momento de crear el usuario en f2670f0fa7909d86de66e7130fe5847c7dfc46ac

**Comment by luisdavid1962** [comment]
Please indícame ¿cuales son esos permisos? para hacerlo con los próximos
que vamos a crear


Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts

**Comment by SpectralAngel** [comment]
Estos permisos no se ven directamente en la GUI, son unos internos de la
base de datos, se supone que a los nuevos ya se los autoasigna

Carlos Flores
