### ISSUE TITLE
Severidad 2 - Desactivar consultorios

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#124]
Necesitamos desactivar consultorios en la vista de administración, de forma que no se vean en los listbox de los formularios que utilizan el campo Consultorio y que la data en ellos se conserve para estadísticas.

Similar a la columna Activo de la vista de usuarios.

**Comment by luisdavid1962** [comment]
Coloquemos en la vista de consultorios  una columna para saber cuales estan activos e inactivos para no tenervios que estar entrando a uno por uno para saber su estado.

**Comment by SpectralAngel** [comment]
Esto es diferente del error original, para la próxima hay que abrir otro issue, es preferible que sean atómicos para aislarlos facilmente cuando ocurran bugs nuevos debido a cambios
