### ISSUE TITLE
Agregar HEA a consulta

### ISSUE THREAD

**Issue by SpectralAngel** [SpectralAngel/hospicloud#128]
Submitter: fany bulnes
Email: fany.bulnes@epsmedical.com
debe existir un apartado en el sistema  que diga 
HEA (historia de la enfermedad actual) que seria básicamente en motivo de consulta.
actualmente hemos ingresado esta información en evolución pero no es lo correcto.

**Comment by luisdavid1962** [comment]
Quiero mantener este issue abierto hasta revisarlo con el usuario

**Comment by luisdavid1962** [comment]
no estuvo bien explicado el cambio falta agregar un campo HEA (Historia de la Enfermedad Actual), dejar el de Motivo de consulta, pero de un menor tama;o. La HEA, sdebe ser del tama;o del actual campo Motivo de consulta.

![image](https://cloud.githubusercontent.com/assets/10442175/5826244/e639da2c-a0b6-11e4-9731-8d5a80e7e69c.png)

**Comment by SpectralAngel** [comment]
Fixed in 897f948f60354c0219b9ae99b2993b833c8fc5da
