### ISSUE TITLE
Problemas con el chat

### ISSUE THREAD

**Issue by SpectralAngel** [SpectralAngel/hospicloud#129]
Submitter: Edison Landaverry
Email: edison.landaverry@epsmedical.com
Al momento de entrar al Chat con mi usuario, me sale  que quien esta conectado al chat es la dra. Fany Bulnes

**Comment by SpectralAngel** [comment]
Software de terceras personas

**Comment by luisdavid1962** [comment]
Hola.....

Tu y yo sabemos que es un software de terceros. Pero es una funcionalidad
que está entregándose a los usuarios dentro del sistema y que en este
momento no está funcionando por lo tanto. 1. No podemos darla por cerrada
2. Hay que tratar de encontrar una solución o reemplazarla.

**Comment by SpectralAngel** [comment]
Cambiando a algo más moderno, Scrollback, por favor revisarlo, tiene otros requisitos y parece que requiere inicio de sesión aparte, sin embargo quizás quite muchos dolores de cabeza

**Comment by luisdavid1962** [comment]
ok


Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts

**Comment by SpectralAngel** [comment]
Alguna actualización sobre esto?

**Comment by SpectralAngel** [comment]
Algún cambio sobre la forma en que funciona?
