### ISSUE TITLE
Severidad 2 - Filtrar consultorios

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#130]
En los formularios de citas y en todo otro en el que se utilicen los consultorios, filtrar solo los consultorios activos.

![image](https://cloud.githubusercontent.com/assets/10442175/5741682/4b4e630e-9bd2-11e4-977e-2507c6fc3f3f.png)

![image](https://cloud.githubusercontent.com/assets/10442175/5741711/754babda-9bd2-11e4-8c68-fc091e66b03b.png)

**Comment by SpectralAngel** [comment]
Corregido también en e079ca948146e619aa5797e277813346f216571a
