### ISSUE TITLE
Error Severidad 2 - Secretaria no vé los consultorios asignados

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#131]
El usuario ingresado en el formulario consultorio como secretaria, no ve los consultorios asignados cuando ingresa con su usuario a Clinica/Consultorio

![image](https://cloud.githubusercontent.com/assets/10442175/5780779/e35edcea-9d72-11e4-9bdc-1b89497e765e.png)

![image](https://cloud.githubusercontent.com/assets/10442175/5780793/fb487cd0-9d72-11e4-964e-720056ddf0db.png)

**Comment by SpectralAngel** [comment]
El  commit 8953cfc5d7ad86c7b865bf836466a88c7a8e31e4 agregó la vista para secretarias por favor confirmar

**Comment by luisdavid1962** [comment]
Funciona OK
