### ISSUE TITLE
Error Severidad 2 - Cambios en los botones de las citas y Sala de espera

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#133]
Para forzar al uso de la Sala de Espera, cuando se cree una cita para un paciente en un consultorio, los botones que deben aparecer son ¨"Agregar a Sala de Espera" (esto haría que el nombre del paciente se borre de las citas y aparezca en la Sala de Espera y empiece a contar el tiempo que el paciente esperó) y el otro botón debe decir: "No se presentó a la cita" (el cual marca la cita como se hace actualmente)

y en la Sala de Espera un botón debe decir "No ingresó a consulta" (para ser usado si el paciente, estando en la sala de espera, decide irse y no entra a la cita), "Agregar lectura de signos" (esto lo puede hacer el doctor o la enfermera y es opcional) y "A consulta" que se presionará cuando el paciente ingrese a atenderse con el Médico.

Cuando un paciente es asignado a la Sala de Espera, debería aparecer su hora de la cita, para que la enfermera tome preferencia en el ingreso al que está en su hora de cita sobre el que llegó sin cita o que la perdió.

Debería haber una tercera sección que diga "Atendiendo a", de forma que se pueda saber quien está con el doctor atendiéndose en ese momento y debe sacar al paciente de la Sala de Espera y ponerlo en este lugar hasta que termine su consulta.Existirá un botón, para dar por terminada la cita (con este dato podremos medir el tiempo de atención de cada médico)

![image](https://cloud.githubusercontent.com/assets/10442175/5787533/f03317ec-9dc7-11e4-9fd0-7d7542fc4e3f.png)

**Comment by SpectralAngel** [comment]
Agregar a sala de espera es parte del software a partir del commit mencionado anteriormente
