### ISSUE TITLE
Error Severidad 3 - Mejorar vista de productos en Inventario

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#135]
En la administración, para el ingreso de los productos, necesitamos poder ordenar la columna con los nombres de los productos (por falta de esto, se han introducido 2 o mas veces el mismo producto).

Necesitamos un campo de activo, que se muestre en la vista de ingreso de productos y que en los listbox, se filtren para que los no activos no aparezcan.

![image](https://cloud.githubusercontent.com/assets/10442175/5787776/7fee7262-9dd4-11e4-9977-911f67ff4e26.png)

**Comment by SpectralAngel** [comment]
Corregido en 9cdda2e4c2da638e16322263b13cbd81d2673e2b, por favor comprobar

**Comment by luisdavid1962** [comment]
Hay un error en el nombre del campo al momento de abroir la vista de los Item Templates

FieldError at /admin/inventory/itemtemplate/
Cannot resolve keyword 'decripcion' into field. Choices are: acciones, activo, cargos, cobros, comision, comision2, comprado, consultorio_cargos, costo, created, descripcion, devoluciones, habitaciones, historicos, honorarios, id, impuestos, item_type, items, marca, medicamentos, modelo, modified, notas, oxigeno_terapias, precio_de_venta, radiologo, requisiciones, suppliers, tecnico, tipoexamen, tipos_pago, transferidos, unidad_de_medida, usuarios, ventas
Request Method:	GET
Request URL:	http://hospinet.epsmedical.com/admin/inventory/itemtemplate/
Django Version:	1.7.2
Exception Type:	FieldError
Exception Value:	
Cannot resolve keyword 'decripcion' into field. Choices are: acciones, activo, cargos, cobros, comision, comision2, comprado, consultorio_cargos, costo, created, descripcion, devoluciones, habitaciones, historicos, honorarios, id, impuestos, item_type, items, marca, medicamentos, modelo, modified, notas, oxigeno_terapias, precio_de_venta, radiologo, requisiciones, suppliers, tecnico, tipoexamen, tipos_pago, transferidos, unidad_de_medida, usuarios, ventas
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in raise_field_error, line 1433
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/local/lib/python2.7/dist-packages/django_select2_forms-1.1.14-py2.7.egg',
 '/usr/lib/python2.7/dist-packages',
 '/home/ubuntu/src/django-extra-views',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/home/ubuntu/hospicloud/hospinet']
Server time:	Lun, 19 Ene 2015 16:34:36 -0600

**Comment by SpectralAngel** [comment]
Corrigiendo en 814e0c09363187eaf5a587dec76d91cd9c622777
