### ISSUE TITLE
Error Severidad 4 - Agregar botón de producto nuevo

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#137]
El formulario para ingresar un producto no existente

![image](https://cloud.githubusercontent.com/assets/10442175/5787844/4c7d10c8-9dd9-11e4-9975-8a8807a3cf20.png)

Debería llamarse desde un botón en el formulario de agregar items al inventario

![image](https://cloud.githubusercontent.com/assets/10442175/5787851/d78dc0ea-9dd9-11e4-9c2a-63b862c7b09e.png)

**Comment by luisdavid1962** [comment]
Si bien es cierto ya cumplimos la funcionalidad de poder agregar un producto nuevo desde el inventario de , la forma en que esto ocurre no es muy práctica.

1 se abre una nueva ventana
2 al grabar el producto, no se cierra la ventana
3 tengo que refrescar (F5) la ventana de ingreso de items para que se actualice el listbox.

al presionar el boton de agregar producto, debe abrirse el formulario de producto nuevo, ingresarlo y que al grabar se cierre el formulario y refresque el formulario de ingreso de productos.

El  menor esfuerzo,  no siempre es la mejor manera.

**Comment by SpectralAngel** [comment]
Fixed on 658863f6e0a7cd3c258aebdd14024e97049e7893

**Comment by luisdavid1962** [comment]
está correcto

**Comment by luisdavid1962** [comment]
Pasa lo mismo que en requisición, va a la pantalla de edicion del producto
![image](https://cloud.githubusercontent.com/assets/10442175/5866288/6b712a34-a255-11e4-9097-00cb7bbd3708.png)

en lugar de volver al ingreso del producto en donde estaba

**Comment by luisdavid1962** [comment]
lo cerramos porque será tratado de otra forma en el nuevo cambio para los inventarios
