### ISSUE TITLE
Error Severidad 4 - Agregar botón de producto nuevo en compras

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#138]
En el formulario en el que se ingresan los productos comprados agregar el botón de producto nuevo

![image](https://cloud.githubusercontent.com/assets/10442175/5787932/261db7b6-9dde-11e4-98e1-82613917e104.png)

que debe abrir el siguiente formulario
![image](https://cloud.githubusercontent.com/assets/10442175/5787938/a160c6c0-9dde-11e4-818a-9d276d2fafbe.png)

**Comment by luisdavid1962** [comment]
Si bien es cierto ya cumplimos la funcionalidad de poder agregar un producto nuevo desde las compras, la forma en que esto ocurre no es muy práctica.

1 se abre una nueva ventana
2 al grabar el producto, no se cierra la ventana
3 tengo que refrescar (F5) la ventana de compras para que se actualice el listbox.

al presionar el boton de agregar producto, debe abrirse el formulario de producto nuevo, ingresarlo,  que al grabar se cierre el formulario y refresque el formulario de ingreso de productos a las compras.

El  menor esfuerzo,  no siempre es la mejor manera.

**Comment by SpectralAngel** [comment]
Fixed in 658863f6e0a7cd3c258aebdd14024e97049e7893

**Comment by luisdavid1962** [comment]
igual a requisiciones e ingreso a inventario

**Comment by luisdavid1962** [comment]
lo cerramos porque será tratado de otra forma en el nuevo cambio para los inventarios
