### ISSUE TITLE
Error Severidad 4 - Ordenar formulario de ingreso de producto

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#140]
Colocar el campo de inventario arriba, al medio Item y cantidad al final y que cuando el formulario abra, colocar por default el cursor en el campo "item"

![image](https://cloud.githubusercontent.com/assets/10442175/5788038/7706501e-9de5-11e4-8b1a-cdbdddee98f4.png)

**Comment by luisdavid1962** [comment]
El formulario continúa igual, no se ha aplicado el cambio.

**Comment by SpectralAngel** [comment]
Puedes darme una URL completa de donde esta el formulario, creo que cambie
otro que no era

Carlos Flores

**Comment by luisdavid1962** [comment]
http://hospinet.epsmedical.com/inventory/14/item/agregar

**Comment by SpectralAngel** [comment]
Fixed in 658863f6e0a7cd3c258aebdd14024e97049e7893
