### ISSUE TITLE
Cambios Importancia 0 - Implementar cambios en Contratos y crear planes.

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#147]
Bàsicamente el proceso debería ser el siguiente:

1. Crear un "plan", que será el que contenga los beneficios y precios especiales, todo beneficio no contemplado en estos planes, será cobrado a los precios que tenga especificados la EPS. Se puede poner un valor o un descuento, no ambos. Luego se usarán estos campos para hacer facturas si es necesario.

![image](https://cloud.githubusercontent.com/assets/10442175/6015303/e46f44ac-ab38-11e4-8f22-66514c613a1c.png)

2. Crear un "contrato maestro" que será el template de los contratos que se crearán para cada persona que se quiera incorporar., estos contratos no deben hacer ninguna diferencia si son empresariales  o particulares. Los llamados contratos particulares, deberían tener como empresa a la EPS.

![image](https://cloud.githubusercontent.com/assets/10442175/6014282/ad12c932-ab26-11e4-83c8-626e13c5a501.png)

3. Debería existir un formulario, para crear contratos en forma masiva,que permita seleccionar el nombre de un contrato maestro y un archivo en excel o csv de un formato específico que levante todas las personas del archivo y les cree un contrato para cada uno.  El campo contratante no puede quedar en blanco (aqui van los nombres de la empresa  que contrata el seguro o EPS Medical si es una venta individual o por EPS)

4. Debe existir un reporte que muestre los "Contratos Maestros" vencidos

5. Cada vez que nos envíen una actualización de afiliados, debe existir un proceso que permita, cargar el archivo de excel o csv (el mismo formato de la carga inicial) y que agregue las personas nuevas, que cambie la fecha de vencimiento a las existentes y deje la fecha vencida y camcele el contrato para las que no figuran en el archivo.

6. Debería existir una forma manual para dar de alta, renovar o dejar vencer los contrato de las personas

**Comment by SpectralAngel** [comment]
Vo a separar esto en tareas, para que sea más fácil llevar control sobre los avances

**Comment by luisdavid1962** [comment]
Ok... como te parezca mejor.... solo que tengo una pulga en la oreja que
está presionando porque estén los del ministerio en la base.... ☺

**Comment by SpectralAngel** [comment]
Una pregunta, que es el administrador de poliza?

**Comment by luisdavid1962** [comment]
es Mediprocesos en este cas....

el intermediario entre la Cia de Seguros y nosotros

2015-02-04 10:27 GMT-06:00 Carlos Flores <notifications@github.com>:

> Una pregunta, que es el administrador de poliza?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpectralAngel/hospicloud/issues/147#issuecomment-72886313>
> .
>



-- 
Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com/>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts

**Comment by SpectralAngel** [comment]
La creación automática para contratos está lista, nada más falta el cambio en la interfaz de paciente

**Comment by luisdavid1962** [comment]
Tenemos que revisar esto
