### ISSUE TITLE
Cambios Importancia 1 - Cambios en formulario de personas

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#148]
Agregar en el formulario, despues de los datos personales, una sección de contrato que refleje los contratos que la persona puede tener con EPS Medical, los beneficios a los que tiene derecho y acceso a los detalles de sus contratos.

Persona sin contrato
![image](https://cloud.githubusercontent.com/assets/10442175/6015352/98e894ec-ab39-11e4-9e05-a8b59cb71f85.png)

Persona con contratos (deben salir ordenados por número, primero los activos)
![image](https://cloud.githubusercontent.com/assets/10442175/6015079/afeab066-ab35-11e4-8069-6f527e7171bd.png)

El numero del contrato es un link que nos lleva al contrato, tal como está ahora.
![image](https://cloud.githubusercontent.com/assets/10442175/6015088/d658e6a0-ab35-11e4-9ec8-ae333dbbf6e6.png)

Al pasar el mouse sobre el nombre del plan, debería salir una ventana con los beneficios
![image](https://cloud.githubusercontent.com/assets/10442175/6015245/e0163952-ab37-11e4-8400-4e7d613e6d0d.png)

Los links azules deben cambiarse por
![image](https://cloud.githubusercontent.com/assets/10442175/6015493/9b0ca8a2-ab3a-11e4-8841-841624c99487.png)

Donde "datos personales", lleva a la pantalla antes descrita.
"Caract y Antecedentes", abrirá un formulario con esas secciones:( Características físicas, Antecedentes personales, antecedentes familiares, antecedentes quirurgicos y antecedentes Gineco-obstétricos.
"Emergencias", "Hospitalizaciones" e "imágenes" (llevan a lo que dicen) y
"Consultas", muestra los consultorios (por ahora, luego mostrará las consultas de cualquier médico que se hayan realizado con esta persona).
"contratos" desaparece.

**Comment by SpectralAngel** [comment]
En 0410042e95cb2f170584263907076210b97c1567 están los cambios iniciales en la UI del paciente y la persona para mostrar los contratos con sus beneficios, listado en tablas de manera temporal mientras reviso la viabilidad del mouseover (puede que sea problema para algunas personas)
