### ISSUE TITLE
Error Severidad 1 - No se crean citas

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#150]
Al tratar de crear citas en un consultorio, se ingresan todos los datos en el formulario respectivo y al momento de presionar grabar la pantalla queda vac'ia y la cita no se crea

![image](https://cloud.githubusercontent.com/assets/10442175/6160066/7afa8e18-b223-11e4-88b1-e052ac79d0ed.png)

![image](https://cloud.githubusercontent.com/assets/10442175/6160070/8b128fc6-b223-11e4-8e3e-f8be20dbe9aa.png)

![image](https://cloud.githubusercontent.com/assets/10442175/6160046/4ee71daa-b223-11e4-913a-86793f3dd443.png)

**Comment by SpectralAngel** [comment]
Al parecer era una falta de memoria del servidor, marcando como supuestamente arreglado

**Comment by luisdavid1962** [comment]
ok funcionando
