### ISSUE TITLE
ERROR SEVERIDAD 3 - En formulario de personas algunos no aparecen los beneficios

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#153]
En el caso de Karla Yamileth Cueva Motiño no aparecen los cambios relacionados a los beneficios
![image](https://cloud.githubusercontent.com/assets/10442175/6197864/522a014e-b3b3-11e4-8835-db5cda4f2d83.png)

con Antonio Misael Cueb\va Motiño si...

**Comment by SpectralAngel** [comment]
Necesitaré la url del lugar donde no aparece

**Comment by luisdavid1962** [comment]
http://hospinet.epsmedical.com/persona/297

**Comment by SpectralAngel** [comment]
Karla Yamileth no tiene contrato ingresado, marcando como invalido

**Comment by luisdavid1962** [comment]
No entendí ¿que significa marcando como inválido?

2015-02-14 18:36 GMT-06:00 Carlos Flores <notifications@github.com>:

> Karla Yamileth no tiene contrato ingresado, marcando como invalido
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpectralAngel/hospicloud/issues/153#issuecomment-74398585>
> .
>



-- 
Saludos

Ma. Ing. Luis David Santa Maria Loza

EPS Medical
Llame ya 22631111

*Cuidando lo mejor de Honduras, su gente*

  <http://www.epsmedical.com/>http://www.epsmedical.com
<https://www.facebook.com/epsmedical?ref=ts&fref=ts>
https://www.facebook.com/epsmedical?ref=ts&fref=ts
