### ISSUE TITLE
Error Severidad 4 - Arreglo formulario de persona 1

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#154]
Quitar el nombre de la persona  del lado del contrato y poner el plan, a la derecha un campo indicando si es titular o dependiente, y si el contrato está Activo o inactivo, la fecha de vencimiento y en la siguiente linea el nombre del titular (sale su mismo nombre si es el titular)

![image](https://cloud.githubusercontent.com/assets/10442175/6198023/9f753b78-b3b6-11e4-9ee4-2b5b6a112796.png)

**Comment by luisdavid1962** [comment]
Esto es lo que debe aparecer en un formulario persona con contrato asignado.....

Agregar que aparezca la compañía contratante, antes del plan  (como los planes ahora tienen nombres genericos y se han simplificado, necesitamos saber a que compa;'ia pertenece el paciente)

Por favor no olvidar colocar fecha de vencimiento y si es titular o dependiente

**Comment by SpectralAngel** [comment]
Estoy pendiente de agregar vistosidad a la etiqueta de Activo/Inactivo para que sea facil de distinguir
