### ISSUE TITLE
error severidad 2 - No puedo entrar a contratos

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#171]
http://hospinet.epsmedical.com/contracts/

TypeError at /contracts/
Related Field got invalid lookup: empresarial
Request Method:	GET
Request URL:	http://hospinet.epsmedical.com/contracts/
Django Version:	1.7.4
Exception Type:	TypeError
Exception Value:	
Related Field got invalid lookup: empresarial
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py in get_lookup_constraint, line 1574
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7/dist-packages',
 '/home/ubuntu/src/django-extra-views',
 '/home/ubuntu/hospicloud/hospinet/src/django-select2-forms-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/home/ubuntu/hospicloud/hospinet']
Server time:	Jue, 19 Feb 2015 19:43:54 -0600
Error during template rendering

In template /home/ubuntu/hospicloud/hospinet/contracts/templates/contracts/index.html, error at line 95
Related Field got invalid lookup: empresarial
85	                                    <div class="col-md-6">
86	                                        <section class="page-header">
87	                                            <h2>Meta al {{ meta.fecha }}</h2>
88	                                        </section>
89	                                        <ul>
90	                                            <li>
91	                                                Contratos: {{ meta.contratos }}
92	                                            </li>
93	                                            {% for vendedor in vendedores %}
94	                                                <li>
95	                                                    {{ vendedor }}: {{ vendedor.get_contratos_mes }}
96	                                                    contratos
97	                                                </li>
98	                                            {% endfor %}
99	                                        </ul>
100	                                    </div>
101	                                </div>
102	                            </div>
103	                        </article>
104	                        <article id="privados" class="tab-pane">
105	                            <div class="col-md-12">

**Comment by SpectralAngel** [comment]
Fixed with 1b03dde991849c9d044fedf982a1488a4e5e7bcc
