### ISSUE TITLE
Error Severidad 1 - Necesitamos cambiar el campo PCD

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#178]
Al tratar el campo PCD como integer, no tiene suficiente capacidad, convertirlo a Double u otro tipo

DataError at /contracts/archivo/40/procesar
integer out of range
Request Method:	GET
Request URL:	http://hospinet.epsmedical.com/contracts/archivo/40/procesar
Django Version:	1.7.5
Exception Type:	DataError
Exception Value:	
integer out of range
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute, line 65
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7/dist-packages',
 '/home/ubuntu/src/django-extra-views',
 '/home/ubuntu/hospicloud/hospinet/src/django-select2-forms-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-i386-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/home/ubuntu/hospicloud/hospinet']
Server time:	Vie, 27 Feb 2015 22:39:25 -0600

**Comment by SpectralAngel** [comment]
Cambiado de Integer a BigInteger, ahora soporta de -9223372036854775808 to 9223372036854775807
