### ISSUE TITLE
Cambios Importancia 0 - Cambios en vista de personas del administrador

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#183]
En la vista de personas del administrador, Colocar algo para sortear la lista en orden alfabetico o dejarlo en orden de ingreso, colocar una columna con el nombre de la empresa, otro con el numero de contrato y el numero de identidad

![image](https://cloud.githubusercontent.com/assets/10442175/6613260/9e5096f4-c84f-11e4-946b-daf584eb24b8.png)

**Comment by luisdavid1962** [comment]
Una pregunta, el nombre de la empresa, y el numero de contrato ¿no se pueden poner?, porque no son campos de ese formulario???

**Comment by SpectralAngel** [comment]
Si, el nombre de la empresa y el contrato son externos a este formulario, eso es lo que pasa, voy a agregar el id a la lista para que lo puedas ordenar por creación
