### ISSUE TITLE
Error Severidad 1 - No puede crearse una cita de paciente

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#184]
Normalmente, las citas estan funcionnado, El Doctor Edison Landaverry me habia expresado que a las 6.00 pm, el programa deja de funcionarle en las citas... yo no le creía, pero ayer y hoy me ha demostrado que realmente, deja de funcionar... no sé si existe algo que pueda estar ocasionando esto.

![image](https://cloud.githubusercontent.com/assets/10442175/6700310/f91d4d80-ccd1-11e4-91f6-8b5b54cb893c.png)

![image](https://cloud.githubusercontent.com/assets/10442175/6700325/2e21ca2e-ccd2-11e4-83e6-bf31fea14739.png)

![image](https://cloud.githubusercontent.com/assets/10442175/6700341/4b064912-ccd2-11e4-8a8b-44e3ccc016b6.png)

**Comment by SpectralAngel** [comment]
Estoy investigando este problema tan raro, pude duplicarlo pero no entiendo aún por que está ocurriendo

**Comment by luisdavid1962** [comment]
Me comenta la Dra. Fany que ella a veces deja pacientes en la lista de espera porque hay muchos y no hay tiempo para escribir en el sistema y cuando en la noche llega a su casa, ya no est'an. Y tambien le ha pasado que ha llenado informaci'on de pacientes y luego no aparece la informaci'on, como que no hubiera tenido ni cita, no aparece en el consultorio...
