### ISSUE TITLE
Error Severidad 2 - No funciona el boton de enviar a sala de espera

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#185]
En la vista de pacientes de un consultorio, el boton "enviar a Sala de Espera" da el siguiente error

![image](https://cloud.githubusercontent.com/assets/10442175/6741377/90ab2692-ce4c-11e4-872f-bfeab4a9c3b3.png)

**Comment by SpectralAngel** [comment]
voy a ocupar un poco mas de información del traceback, si puedes repetir el error dale a switch to copy-and-paste view y pega el contenido.

**Comment by SpectralAngel** [comment]
Corregido en ac2e55109b5e74668058a9fad3819fa05d206f7c

**Comment by luisdavid1962** [comment]
Ok el botón ya funciona pero el paciente aparece en la Sala de Espera pero no desaparece de la Cita

![image](https://cloud.githubusercontent.com/assets/10442175/6760626/4adfc18a-cf10-11e4-85f9-4b8292f68256.png)
