### ISSUE TITLE
Error Severidad 4 - Correcciones de botones y otros en Vista de personas

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#209]
Cuando ingresemos a la vista de personas, deben aparecer los botones según la imagen

![image](https://cloud.githubusercontent.com/assets/10442175/7171258/61fc33b6-e393-11e4-92d9-eae2eb57f423.png)

1. Desaparecer el boton "Agregar a un consultorio" en lugar de el colocar el boton de "Crear una Cita"
2. El botón "Crear un contrato" debe ser reemplazado por "Agregar a un contrato" y ejecutar las acciones del actual botón "Crear contrato desde Maestro"
3. Desaparecer los demás.

**Comment by SpectralAngel** [comment]
Este cambio ha sido invalidado por la reciente desvinculación de consultorio marcando como invalido
