### ISSUE TITLE
Error Severidad 2 - Boton guardar de edicion de datos

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#215]
Cuando en el formulario de pacientes, se quiere editar un dato de alguna sección, al presionar el boton guardar, se abre la siguiente seccion y así sucesivamente hasta llegar a la ultima.

El boton guardar debería cerrar la seccion en la que se edito el campo y regresar al formulario de paciente que se muestra a continuación.

![image](https://cloud.githubusercontent.com/assets/10442175/7171701/0f324a66-e399-11e4-8610-861208f5dfec.png)

**Comment by SpectralAngel** [comment]
El código para esto ya está implementado, pero es parte de la complicada migración hacia utilización pura de persona,
