### ISSUE TITLE
Cambios Importancia 0 - Cambios en el formulario de Información del paciente

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#224]
Los botones de edición, abren formularios y al cerrar estos, se debe regresar a esta misma pantalla (Antecedentes) no a Datos personales

![image](https://cloud.githubusercontent.com/assets/10442175/7339229/aa70648e-ec24-11e4-80d8-649877550f74.png)

 Los nombres de los botones deberían coincidir con los nombres de las secciones

**Comment by SpectralAngel** [comment]
Te debo el de cambiar de pestaña, solo puedo redireccionar a urls, no ejecutar javascript desde el servidor
