### ISSUE TITLE
Error Severidad 3 - Formulario de Antecedentes patológicos

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#225]
Al presionar el botón de Antecedentes Patológicos Personales se abre un formulario que tiene algunos problemas y errores

![image](https://cloud.githubusercontent.com/assets/10442175/7339243/54e72d6c-ec25-11e4-8092-05a9788d9a00.png)

1. El título dice "Editar Fisico" y debe ser "Editar Antecedentes Patológicos Personales"
2. los campos son de dos tipos unos para marcar y otros para seleccionar ¿por que no hacemos todos iguales para que se vea mejor?
3. Las etiquetas en el formulario de edición y en el resumen de antecedentes no concuerdan
![image](https://cloud.githubusercontent.com/assets/10442175/7339284/de8083d8-ec26-11e4-9623-e4dfbfd4a0e2.png)

4. Faltan campos que estan en el formulario de edición y el de antecedentes

![image](https://cloud.githubusercontent.com/assets/10442175/7339302/632965a0-ec27-11e4-8a94-929acfe7dcbb.png)

5. Si se selecciona un campo como "desconocido" en el resumen de antecedentes, dice NO

**Comment by SpectralAngel** [comment]
En 6f74b1952f35a6aa5e95ca95d1459370df66c714 estan los cambios con respecto al formulario congruente y a los campos faltantes
