### ISSUE TITLE
Cambios Importancia 0 - Botón no se presentó a la cita

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#231]
Este boton
![image](https://cloud.githubusercontent.com/assets/10442175/7352635/34e7dce6-ecca-11e4-87a2-71e24ac6ec71.png)

debería hacer el trabajo de una sola vez yno abrir otro formulario para marcar el check de Ausente y luego dar Guardar

**Comment by luisdavid1962** [comment]
Sigue igual, el formulario sigue apareciendo.....

![image](https://cloud.githubusercontent.com/assets/10442175/7359806/4d05bf1a-ed00-11e4-8aab-5748963ea9a0.png)

**Comment by SpectralAngel** [comment]
Fixed in d010646f8fd1f74ff26179c36c999c4a987e3be4
