### ISSUE TITLE
Error Severidad 1 - Error en la visualizacion de los consultorios

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#235]
El usuario de Erika, que es la enfermera erika.tinoco (con password erika123)  y yo podemos ver los pacientes en la vista de consultorio.

![image](https://cloud.githubusercontent.com/assets/10442175/7360290/22047670-ed06-11e4-8eec-4ab5c6906345.png)

Pero los medicos,,, Edison.Landaverry (con password edison123) o fany.bulnes (con password fany123) no ven nada

![image](https://cloud.githubusercontent.com/assets/10442175/7360309/660a7fae-ed06-11e4-8d43-f5d60666ebc6.png)

**Comment by SpectralAngel** [comment]
No han entrado al consultorio en esa pantalla que muestras alli

**Comment by luisdavid1962** [comment]
si fue un error...
