### ISSUE TITLE
Error Severidad 2 - Lista de pacientes del consultorio

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#237]
el boton Ver de la lista de pacientes del consultorio, abre los formularios de pacientes diferentes al que dice.. por ejemplo el primero a nombre de Mayra Beatriz Chevez Coello al darle ver abre el de JOHNNY VICENTE REYES MUNGUIA

![image](https://cloud.githubusercontent.com/assets/10442175/7360580/ba53bb4a-ed09-11e4-9c7c-37bacf3194b0.png)

![image](https://cloud.githubusercontent.com/assets/10442175/7360576/a37acdb4-ed09-11e4-868b-4f22b2b747fe.png)

**Comment by SpectralAngel** [comment]
Esta vista desaparece por la eliminación del concepto "Paciente", por lo tanto todas las vistas que estas mencionando se procederan a eliminar, en realidad son vistas repetidas de  "Persona"
