### ISSUE TITLE
Cambios Importancia 0 - Documento de paciente (Aun en proceso no tomar en cta hasta que este aviso sea removido)

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#255]
Cuando aparece el documento de paciente, debe ser como la imagen:
Las pestañas en la parte superior y desaparecer Emergencias, Hospitalizaciones, Imágenes, Contratos, Diagnósticos y Ordenes y Prescripciones

![image](https://cloud.githubusercontent.com/assets/10442175/7403631/c3ae60fa-ee94-11e4-85a7-fa313538e8ed.png)

**Comment by SpectralAngel** [comment]
Ya se cargan dinámicamente las pestañas de paciente
