### ISSUE TITLE
Error Severidad 2 - Unificar contratos en pacientes

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#260]
Tenemos pacientes con polizas en el colegio de abogados y en el Ministerio publico.Necesitamos que bajo un solo nombre aparezcan los 2 contratos y esto para cualquier paciente con mas de 1 contrato

![image](https://cloud.githubusercontent.com/assets/10442175/7687124/3a97cfd6-fd58-11e4-8b87-b6ad859427ba.png)

**Comment by SpectralAngel** [comment]
Reportar duplicado hace esto sín ningún problema, transfiere todo de una persona a otra, incluyendo los PCD

**Comment by luisdavid1962** [comment]
El problema es que no puedo estar haciendo esto manualmente... ¿cuando
vuelva a cargar el archivo de importación que pasará? Podemos en el
programa de carga hacer que si el Doc de identidad o los nombres, apellidos
y fecha de nacimiento son iguales se unan los contratos bajo la misma
persona?
