### ISSUE TITLE
Error Severidad 2 - Medico que atiende consulta

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#267]
Necesitamos saber ¿que medico atendió las consultas de un paciente?

Actualmente no hay firma de saberlo

![image](https://cloud.githubusercontent.com/assets/10442175/7895002/0e1714c2-0635-11e5-90ca-b7e8fda963f2.png)

**Comment by SpectralAngel** [comment]
No recuerdo en que commit pero ya se agregó
