### ISSUE TITLE
No funciona agregar beneficiario

### ISSUE THREAD

**Issue by luisdavid1962** [SpectralAngel/hospicloud#327]
Desde la pantalla que te muesto
![image](https://cloud.githubusercontent.com/assets/10442175/12950181/88fb4bc0-cfd1-11e5-87b2-b554ffdc7a9d.png)
 el link de AGREGAR BENEFICIARIO  solo muestra una pantalla en blanco.

**Comment by SpectralAngel** [comment]
Corregido en 55c3d335d3cc7ba4dc51da83d22e10066a0291f2
