### ISSUE TITLE
Agregar datos estadísticos al control presupuestal

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#340]
titulo de la la pagina
ESTADOS FINANCIEROS ANUAL

GRAFICA
 
![captura de pantalla 2016-03-03 a las 13 13 19](https://cloud.githubusercontent.com/assets/5262659/13506080/e631953e-e141-11e5-8d79-129946b831af.png)

URL http://hospinet.epsmedical.com/budget/

**Comment by SpectralAngel** [comment]
En proceso

**Comment by SpectralAngel** [comment]
Completado en 20e7fe2f799600dde31f6c4a061be9d2e9164dbe
