### ISSUE TITLE
Agregar Distintos tipos de Pago

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#343]
Las Formas de pago son 
Mensual  
Reembolso 
Diario

los tipos de pago son
efectivo
cheque
transferencia bancaria
pos

seria importante ponerle link a cada una de estas para poder ver que es cada cosa
url: http://hospinet.epsmedical.com/admin/invoice/tipopago/

**Comment by SpectralAngel** [comment]
No entiendo esta pregunta, el admin se trata de agregar y eliminar datos.

Estos son únicamente una refencia al método que se utiliza para ingresar los pagos, las marcas en los otros campos le indican al programa que hacer con ellos, voy a escribir documentación sobre ellos y pasarla para que tengan referencia.

**Comment by SpectralAngel** [comment]
A esto se refiere este issue:

![image](https://cloud.githubusercontent.com/assets/434838/13548006/baf844e8-e2aa-11e5-813b-ae159e4c33cd.png)
