### ISSUE TITLE
url: http://hospinet.epsmedical.com/persona/51294

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#356]
Diagnóstico, que se puedan enumerar ya sea por letra o número Ya que

actualmente al escribirlo quedan todos juntos y parece que fuera un solo 

diagnóstico.

**Comment by nicolasmolinafranco** [comment]
subir listado de CIE10  que envio en link

http://www.sssalud.gov.ar/hospitales/archivos/cie_10_revi.pdf

**Comment by nicolasmolinafranco** [comment]
crear una casilla de afeccion

**Comment by nicolasmolinafranco** [comment]
FECHA  DIAGNOSTICO CIE10 DIAGNOSTICO CLINICO EDITAR

**Comment by SpectralAngel** [comment]
Esto es un problema de entrenamiento, se pueden agregar una cantidad ilimitada de diagnósticos por consulta, no deberían de poner más de uno en la sección de abajo
