### ISSUE TITLE
PANEL DE CONTROL ASEGURADORAS 1.

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#361]
![captura de pantalla 2016-03-11 a las 10 37 15](https://cloud.githubusercontent.com/assets/5262659/13708914/c79ec4f8-e776-11e5-916d-f0ac8552902e.png)

**Comment by SpectralAngel** [comment]
Vista completada, se encuentra en contrato->aseguradora
