### ISSUE TITLE
quejas

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#366]
http://hospinet.epsmedical.com/rrhh/quejas/

en esta pagina debe estar el boton de aceptar o rechasar

**Comment by SpectralAngel** [comment]
Aceptar o rechazar una queja? no me parece adecuado, aceptarla no tiene sentido en el caso de quejas, únicamente rechazarlas, a lo cual yo lo llamaría invalidar la queja.

La aceptación o rechazo es una característica exclusiva de las soluciones, no podemos mezclar peras y naranjas, la interfaz se volvería super confusa.

Cuando una solución es aceptada, automáticamente su queja se marca como solucionada.
