### ISSUE TITLE
historia Fisica Metabolica

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#372]
http://hospinet.epsmedical.com/persona/51074

![captura de pantalla 2016-03-18 a las 17 12 55](https://cloud.githubusercontent.com/assets/5262659/13894387/ce38acbe-ed2c-11e5-8d1c-3a2857bf866b.png)

**Comment by SpectralAngel** [comment]
Completado

**Comment by SpectralAngel** [comment]
Completado en 0c30ba7d6d01da2fac421132f0b8256deb63e72f
