### ISSUE TITLE
modificaciones panel de control operacion clincia

### ISSUE THREAD

**Issue by nicolasmolinafranco** [SpectralAngel/hospicloud#373]
http://universidad.epsmedical.com/consultorio/mensual?year=2016&mes=3&submit=Marzo

- link total de consultas

- link total consultas por ciudad

- link total de quejas me tira a link 
http://universidad.epsmedical.com/income/cheque/periodo?  no tiene nada que ver?

- link total consultas por aseguradora

- link numero de consulta por medico

- link numero de consulta por enfermera

**Comment by nicolasmolinafranco** [comment]
- link de total de consultas

- link de total por ciudad
cambiar poliza por aseguradora
cambiar usuario x ciudad en el titulo
instalar tabla y grafica al inicio de la ciudad
![captura de pantalla 2016-03-29 a las 20 18 52](https://cloud.githubusercontent.com/assets/5262659/14129898/a11423b8-f5eb-11e5-91bf-81d6d11884c8.png)
![captura de pantalla 2016-03-29 a las 20 18 39](https://cloud.githubusercontent.com/assets/5262659/14129901/a8afa53e-f5eb-11e5-89a1-caf5f05b7378.png)

- quejas por area da error

- consulta x medicos
cambiar poliza x aseguradora
cambiar usuario x

**Comment by SpectralAngel** [comment]
Voy a separar esto en dos issues, una es una característica nueva la otra correcciones sobre lo desarrollado
